width = 1200
height = 900

iterations = 1
pixel_samples = 4
bounce_samples = 200
bounces = 6

background_color = [0, 0, 0]
epsilon = 1e-10

[camera]
position = [0, 9, 40]
rotation = [0, -3, 0]
scale = [1, 1, 1]
field_of_view = 30


[[planes]]  # left
position = [-10, 0, 0]
rotation = [0, 0, 90]
color = [0.1, 0.2, 0.0]

[[planes]]  # top
position = [0.0, 15.0, 0.0]
rotation = [0, 0, 0]
color = [0.9, 0.9, 0.9]

[[planes]]  # right
position = [10, 0, 0]
rotation = [0, 0, 90]
color = [0.2, 0.1, 0.0]

[[planes]]  # bottom
position = [0, 0, 0]
rotation = [0, 0, 0]
color = [0.9, 0.9, 0.9]

[[planes]]  # back
position = [0, 0, -15]
rotation = [0, 90, 0]
color = [0.9, 0.9, 0.9]

[[planes]]  # front
position = [0, 0, 41]
rotation = [0, 90, 0]
color = [0, 0, 0]


[[spheres]]  # light
position = [0.0, 54.8, 0.0]
radius = 40
emission = [20, 20, 20]

[[spheres]]  # mirror
position = [-4.25, 3.25, -4.0]
radius = 3.25
color = [1, 1, 1]
specular = 1

[[spheres]]  # glass
position = [4.25, 3.25, 2.0]
radius = 3.25
color = [1, 1, 1]
refraction = 1
