[package]
name = "pathtracer"
version = "0.0.0"
edition = "2021"

[profile.release]
codegen-units = 1
lto = true

[dependencies]
nalgebra = "0.31"
png = "0.17"
rand = "0.8"
rand_xoshiro = "0.6"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
